// Generated by flutter-kmp. Do not modify.

import 'dart:async';
import 'dart:convert';
import 'package:iso_duration/iso_duration.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'models.dart';
               
class MySecondTestModule {
  final methodChannelToNative = const MethodChannel("MySecondTestModule");
  
  final Stream<int> intEvents = const EventChannel('MySecondTestModule_intEvents')
    .receiveBroadcastStream()
    .map((event) => jsonDecode(event) as int);
final Stream<MyDataClass> dataClassEvents = const EventChannel('MySecondTestModule_dataClassEvents')
    .receiveBroadcastStream()
    .map((event) => MyDataClass.fromJson(jsonDecode(event) as Map<String, dynamic>));
  
  Future<String> testMethod() async {
    
    final invokeResult = await methodChannelToNative.invokeMethod<String>(
        'testMethod',
        [],
    );

    if (invokeResult == null) {
        throw PlatformException(code: '1', message: 'Method testMethod failed');
    }

    final result = invokeResult;

    return result;
}
}