package de.voize.flutterkmp.ksp.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.symbol.KSValueParameter
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo
import io.outfoxx.swiftpoet.DeclaredTypeName

class IOSKotlinModuleGenerator {
    private fun String.iosModuleClassName() = this + "IOS"

    fun generateModule(
        flutterModule: FlutterKMPSymbolProcessor.FlutterModule,
        constructorParameters: List<KSValueParameter>,
        constructorInvocation: CodeBlock,
        codeGenerator: CodeGenerator,
    ) {
        val packageName = flutterModule.wrappedClassDeclaration.packageName.asString()
        val wrappedClassName = flutterModule.wrappedClassDeclaration.simpleName.asString()
        val className = wrappedClassName.iosModuleClassName()
        val wrappedModuleVarName = "wrappedModule"
        val pluginInstanceConstructorArgName = "pluginInstance"
        val registrarConstructorArgName = "registrar"
        val channelVarName = "channel"

        val classSpec = TypeSpec.classBuilder(className).apply {
            addAnnotation(ExperimentalForeignApi)
            if (flutterModule.isInternal) {
                addModifiers(KModifier.INTERNAL)
            }
            primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(
                        registrarConstructorArgName,
                        FlutterPluginRegistrar,
                    )
                    .addParameter(pluginInstanceConstructorArgName, FlutterPlugin)
                    .addParameters(constructorParameters.map { it.toParameterSpec() })
                    .build()
            )
            addProperty(
                PropertySpec.builder(
                    wrappedModuleVarName,
                    ClassName(packageName, wrappedClassName)
                ).addModifiers(KModifier.PRIVATE).initializer(constructorInvocation).build()
            )
            addInitializerBlock(
                CodeBlock.builder().apply {
                    addStatement(
                        "val $channelVarName = %T(%S, %L)",
                        FlutterMethodChannel,
                        flutterModule.moduleName,
                        "$registrarConstructorArgName.messenger()",
                    )
                    addStatement(
                        "%L.addMethodCallDelegate(%L as %T, %L)",
                        registrarConstructorArgName,
                        pluginInstanceConstructorArgName,
                        NSObject,
                        channelVarName,
                    )
                }.build()
            )
            addFunction(
                FunSpec.builder("handleMethodCall")
                    .addParameter("call", FlutterMethodCall)
                    .addParameter("result", FlutterResult)
                    .returns(Boolean::class)
                    .addCode(
                        CodeBlock.builder().apply {
                            beginControlFlow("return when (call.method)")
                            flutterModule.flutterMethods.forEach { method ->
                                addMethodCodeBlock(
                                    method,
                                    wrappedModuleVarName,
                                    resultStatement = { resultParameter ->
                                        "result!!($resultParameter)"
                                    },
                                    append = { addStatement("true") }
                                )
                            }
                            addStatement("else -> false")
                            endControlFlow()
                        }.build()
                    )
                    .build()
            )
        }.build()

        val fileSpec = FileSpec.builder(packageName, className)
            .addFileComment("Generated by flutter-kmp. Do not modify.")
            .addType(classSpec)
            .build()

        fileSpec.writeTo(codeGenerator, false)
    }
}

private val ExperimentalForeignApi = ClassName("kotlinx.cinterop", "ExperimentalForeignApi")
private val NSObject = ClassName("platform.darwin", "NSObject")

private val FlutterResult = ClassName("flutter", "FlutterResult")
private val FlutterMethodCall = ClassName("flutter", "FlutterMethodCall")
private val FlutterMethodChannel = ClassName("flutter", "FlutterMethodChannel")
private val FlutterPluginRegistrar = ClassName("flutter", "FlutterPluginRegistrarProtocol")
private val FlutterPlugin = ClassName("flutter", "FlutterPluginProtocol")