package de.voize.flutterkmp.ksp.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSValueParameter
import io.outfoxx.swiftpoet.DeclaredTypeName
import io.outfoxx.swiftpoet.FileSpec
import io.outfoxx.swiftpoet.FunctionSpec
import io.outfoxx.swiftpoet.Modifier
import io.outfoxx.swiftpoet.ParameterSpec
import io.outfoxx.swiftpoet.TypeSpec

class IOSModuleGenerator {
    private fun String.iosModuleClassName() = this + "IOS"

    fun generateModule(
        flutterModule: FlutterKMPSymbolProcessor.FlutterModule,
        constructorParameters: List<KSValueParameter>,
        codeGenerator: CodeGenerator,
    ) {
        val packageName = flutterModule.wrappedClassDeclaration.packageName.asString()
        val wrappedClassName = flutterModule.wrappedClassDeclaration.simpleName.asString()
        val className = wrappedClassName.iosModuleClassName()
        val wrappedModuleVarName = "wrappedModule"

        val classSpec = TypeSpec.classBuilder(className).apply {
            if (flutterModule.isInternal) {
                addModifiers(Modifier.INTERNAL)
            }
            addProperty(
                wrappedModuleVarName,
                DeclaredTypeName.typeName("shared.$wrappedClassName"),
                Modifier.PRIVATE
            )
            addFunction(
                FunctionSpec.constructorBuilder().apply {
                    addParameter("pluginInstance", FlutterPlugin)
                    addParameter("registrar", FlutterPluginRegistrar)
                    addParameters(constructorParameters.map {
                        ParameterSpec.builder(
                            it.name?.asString() ?: error("Parameter must have a name"),
                            DeclaredTypeName.qualifiedTypeName(
                                it.type.resolve().declaration.qualifiedName?.asString() ?: error("Parameter must have a type")
                            ),
                        ).build()
                    })
                    addCode("""
let channel = FlutterMethodChannel(name: "${flutterModule.moduleName}", binaryMessenger: registrar.messenger())
registrar.addMethodCallDelegate(pluginInstance, channel: channel)
$wrappedModuleVarName = $wrappedClassName(${constructorParameters.joinToString { it.name?.asString() ?: "" }})
${"\n"}
""".trimIndent()
                    )
                }.build()
            )
            /*
            addFunction(
                FunctionSpec.builder("handle")
                    .addParameter("call", FlutterMethodCall)
                    .addParameter("result", FlutterResult)

                        public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
            switch call.method {
                case "getPlatformVersion":
                result("iOS " + UIDevice.current.systemVersion)
                default:
                result(FlutterMethodNotImplemented)
            }
        }
            )
             */
        }.build()

        val fileSpec = FileSpec.builder(packageName, className)
            .addComment("Generated by flutter-kmp. Do not modify.")
            .addType(classSpec)
            .build()

        val stream = codeGenerator.createNewFile(
            Dependencies.ALL_FILES,
            "flutterkmp",
            flutterModule.moduleName,
            extensionName = "swift",
        )
        stream.write(fileSpec.toString().toByteArray())
        stream.close()

    }
}

private val FlutterResult = DeclaredTypeName.typeName("Flutter.FlutterResult")
private val FlutterMethodCall = DeclaredTypeName.typeName("Flutter.FlutterMethodCall")
private val FlutterPlugin = DeclaredTypeName.typeName("Flutter.FlutterPlugin")
private val FlutterPluginRegistrar = DeclaredTypeName.typeName("Flutter.FlutterPluginRegistrar")