name: Publish artifacts
on:
  release:
    types: [published]
jobs:
  publish-maven:
    name: Build and publish to Maven Repository
    runs-on: macos-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Release build
        run: ./gradlew build
        working-directory: kotlin
      - name: Publish to MavenCentral
        run: ./gradlew publishAllPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        working-directory: kotlin
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_SIGNING_KEY: ${{ secrets.SIGNING_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
