name: Test workflow
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - run: ./gradlew build
  build-example-project:
    name: Build example KMP project
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - run: ./gradlew build
        working-directory: example
  build-android-example-flutter-plugin-example-app:
    name: Build example Android app for the Flutter plugin of the example KMP project
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter build apk
        working-directory: example/flutter/example